name: Run Weather ETL DAG with Soda

on:
  workflow_dispatch:

jobs:
  run-weather-dag:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "apache-airflow==2.9.3" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.3/constraints-3.11.txt"
          pip install soda-core
          pip install -r requirements.txt

      # 4️⃣ Create Airflow home and copy DAGs
      - name: Setup Airflow Home
        run: |
          mkdir -p airflow_home/dags
          cp _05_dags/weather_pipeline_dag.py airflow_home/dags/

      # 5️⃣ Initialize Airflow DB
      - name: Initialize Airflow
        run: |
          export AIRFLOW_HOME=$GITHUB_WORKSPACE/airflow_home
          python -m airflow db migrate

      # 6️⃣ Trigger the Weather DAG
      - name: Trigger Weather DAG
        run: |
          export AIRFLOW_HOME=$GITHUB_WORKSPACE/airflow_home
          python -m airflow dags trigger weather_pipeline

      # 7️⃣ Sleep (wait for DAG to run)
      - name: Sleep
        run: sleep 30

      # 8️⃣ Upload Soda Reports
      - name: Upload Soda Reports
        uses: actions/upload-artifact@v4
        with:
          name: soda-reports
          path: ./_06_Soda_reports
