name: Run Weather ETL DAG

on:
  workflow_dispatch:  # manual trigger

jobs:
  run-dag:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3️⃣ Upgrade pip
      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      # 4️⃣ Install Apache Airflow with constraints
      - name: Install Apache Airflow
        run: |
          pip install "apache-airflow==2.9.3" \
            --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.3/constraints-3.11.txt"

      # 5️⃣ Create airflow_home and copy DAG
      - name: Prepare Airflow DAGs folder
        run: |
          mkdir airflow_home\dags
          copy Dataops_framework\05_dags\weather_pipeline_dag.py airflow_home\dags\

      # 6️⃣ Init Airflow DB
      - name: Initialize Airflow DB
        run: python -m airflow db migrate

      # 7️⃣ Trigger the DAG
      - name: Trigger Weather DAG
        run: python -m airflow dags trigger weather_pipeline

      # 8️⃣ Upload Soda/Logs artifacts
      - name: Upload logs
        uses: actions/upload-artifact@v4
        with:
          name: airflow-logs
          path: airflow_home\logs
