name: Run Weather ETL DAG

on:
  workflow_dispatch:  # allows manual trigger

jobs:
  run-dag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "apache-airflow==2.9.3" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.9.3/constraints-3.11.txt"
          pip install soda-core

      - name: Prepare Airflow environment
        run: |
          export AIRFLOW_HOME=$GITHUB_WORKSPACE/airflow_home
          mkdir -p $AIRFLOW_HOME/dags
          cp -r $GITHUB_WORKSPACE/_05_dags/*.py $AIRFLOW_HOME/dags/
          echo "Copied DAGs to $AIRFLOW_HOME/dags"
          airflow db init

      - name: Add repo root to PYTHONPATH
        run: |
          echo "PYTHONPATH before: $PYTHONPATH"
          export PYTHONPATH=$GITHUB_WORKSPACE:$PYTHONPATH
          echo "PYTHONPATH after: $PYTHONPATH"
          airflow dags list

      - name: Run Weather ETL DAG
        env:
          AIRFLOW_HOME: ${{ github.workspace }}/airflow_home
          PYTHONPATH: ${{ github.workspace }}:${{ env.PYTHONPATH }}
        run: |
          airflow dags list
          airflow dags trigger -e 2025-10-04 weather_pipeline
