name: Run Weather ETL DAG with Soda

on:
  workflow_dispatch:

jobs:
  run-weather-dag:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Install dependencies (Airflow + Soda + Pendulum)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pendulum<3"
          pip install "apache-airflow[all]==2.7.3" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.7.3/constraints-3.11.txt"
          pip install soda-core
          pip install -r requirements.txt

      # 4️⃣ Set AIRFLOW_HOME
      - name: Set Airflow Home
        run: mkdir airflow_home
        shell: powershell

      # 5️⃣ List DAG folder (debug)
      - name: List DAG folder
        run: dir 05_dags
        shell: powershell

      # 6️⃣ Copy DAGs to AIRFLOW_HOME
      - name: Copy DAGs
        run: |
          mkdir airflow_home\dags
          copy 05_dags\weather_pipeline_dag.py airflow_home\dags\
        shell: powershell

      # 7️⃣ Initialize Airflow DB (upgrade + default connections)
      - name: Initialize Airflow
        env:
          AIRFLOW_HOME: ${{ github.workspace }}\airflow_home
        run: |
          python -m airflow db upgrade
          python -m airflow connections create-default-connections

      # 8️⃣ Trigger Weather DAG
      - name: Trigger Weather DAG
        env:
          AIRFLOW_HOME: ${{ github.workspace }}\airflow_home
        run: python -m airflow dags trigger weather_pipeline

      # 9️⃣ Sleep to allow DAG to start
      - name: Sleep
        run: Start-Sleep -Seconds 30
        shell: powershell

      # 🔟 Ensure Soda Reports folder exists
      - name: Ensure Soda Reports folder exists
        run: mkdir 06_Soda_reports
        shell: powershell

      # 1️⃣1️⃣ Upload Soda Reports as artifacts
      - name: Upload Soda Reports
        uses: actions/upload-artifact@v4
        with:
          name: soda-reports
          path: ./06_Soda_reports
