name: Run Weather ETL DAG with Soda

on:
  workflow_dispatch:  # allows manual trigger from GitHub UI

jobs:
  run-weather-dag:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install "pendulum<3" apache-airflow==2.7.3
          pip install soda-core
          pip install -r requirements.txt

      # 4️⃣ Initialize Airflow DB
      - name: Initialize Airflow
        run: airflow db init

      # 5️⃣ Trigger the Weather DAG
      - name: Trigger Weather DAG
        run: airflow dags trigger weather_pipeline

      # 6️⃣ Wait a few seconds to let DAG start
      - name: Sleep
        run: timeout /t 30

      # 7️⃣ Upload Soda Reports as artifacts
      - name: Upload Soda Reports
        uses: actions/upload-artifact@v4
        with:
          name: soda-reports
          path: ./06_Soda_reports  # relative path inside the git repo
