name: Run Weather ETL DAG

on:
  workflow_dispatch:

jobs:
  run-dag:
    runs-on: ubuntu-latest

    env:
      AIRFLOW_HOME: ${{ github.workspace }}/airflow_home
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libpq-dev python3-dev libffi-dev libssl-dev graphviz

      - name: Upgrade pip and install pre-built binaries
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # Force pip to use wheels
          pip install --only-binary=:all: Cython

      - name: Install Python dependencies (wheels only)
        run: |
          pip install --only-binary=:all: \
            "apache-airflow==2.9.3" \
            pandas numpy psycopg2-binary soda-sql

      - name: Setup Airflow directories
        run: |
          mkdir -p $AIRFLOW_HOME/dags
          mkdir -p $AIRFLOW_HOME/logs
          mkdir -p $AIRFLOW_HOME/plugins
          cp -r e_dags/* $AIRFLOW_HOME/dags/

      - name: Initialize Airflow DB
        run: airflow db init

      - name: List all DAGs
        run: airflow dags list

      - name: Trigger Weather ETL DAG
        run: airflow dags trigger weather_pipeline
